#!/usr/bin/env bash
# Render a structured PR body from a bd issue.
# Usage: scripts/render-pr-body.sh <bd-id>
# Output: markdown on stdout.
set -euo pipefail

BD_ID="${1:?Usage: $0 <bd-id>}"

# bd show returns a JSON array; grab the first element as a JSON object.
# Capture bd output separately so we can produce a clean error message
# regardless of whether bd itself errors or just returns [].
if ! ISSUE_JSON="$(bd show "$BD_ID" --json 2>/dev/null)"; then
  echo "Error: bd issue '$BD_ID' not found" >&2
  exit 1
fi
ISSUE="$(jq -c '.[0] // empty' <<<"$ISSUE_JSON")"
if [ -z "$ISSUE" ] || [ "$ISSUE" = "null" ]; then
  echo "Error: bd issue '$BD_ID' not found" >&2
  exit 1
fi

TITLE="$(jq -r '.title' <<<"$ISSUE")"
BODY="$(jq -r '.description // ""' <<<"$ISSUE")"
LABELS="$(jq -r '.labels[]? // empty' <<<"$ISSUE" 2>/dev/null || true)"

# Pull review-pass entries from notes (chronological)
PASS_NOTES="$(jq -r '.notes[]? | .body | select(test("review-pass:"))' <<<"$ISSUE" 2>/dev/null || true)"
if [ -z "$PASS_NOTES" ]; then
  CURRENT_PASS=0
  PASS_NOTES="- Pass 1: not yet submitted"
else
  CURRENT_PASS="$(grep -c "submitted" <<<"$PASS_NOTES" 2>/dev/null || echo 0)"
fi

# Format gate checkboxes from labels
gate_check() {
  local gate="$1"
  if grep -qx "gate:$gate" <<<"$LABELS" 2>/dev/null; then echo "- [ ] $gate"
  else echo "- [x] $gate"; fi
}

cat <<EOF
## What changed
<filled in by impl team at pr-ready>

## Why
$BODY

## How
<filled in by impl team at pr-ready>

## Review passes
**Current pass:** $CURRENT_PASS
$PASS_NOTES

## bd issue
$BD_ID — $TITLE

## Gates
$(gate_check review)
$(gate_check qa)
$(gate_check evals)

🤖 Generated by orchestrator. Do not merge manually — bd-state wins.
EOF
